// Veblen — sample dataset
window.VEBLEN_DATA = (function () {
  const items = [
    {
      id: "abk-cardigan",
      brand: "A.B. Knit Co.",
      name: "Shetland Crewneck Cardigan, Heather Moss",
      category: "Knitwear",
      grade: "excellent",
      gradeScore: 92,
      price: 142, was: 295, discount: 52,
      material: "100% Shetland wool",
      naturalPct: 100,
      origin: "Hawick, Scotland",
      construction: "Fully-fashioned, hand-linked",
      stock: "In stock — sizes S, M, L",
      retailer: "Drake's", sizes: ["XS","S","M","L","XL"],
      flag: null,
      reasoning: [
        ["Material", "+22", "100% wool, no synthetic blends"],
        ["Origin", "+18", "Made in Scotland, traditional knitting region"],
        ["Construction", "+14", "Fully-fashioned panels, hand-linked seams"],
        ["Price History", "+12", "52% off — lowest price in 18 months"],
        ["Brand markup", "−4", "Heritage brand pricing premium"],
      ],
      history: [310,310,295,295,295,280,280,295,295,260,260,295,295,260,210,180,160,150,142],
    },
    {
      id: "drk-oxford",
      brand: "Caldwell & Sons",
      name: "Pinpoint Oxford Cloth Shirt, Pale Blue",
      category: "Shirting",
      grade: "great",
      gradeScore: 78,
      price: 88, was: 195, discount: 55,
      material: "100% long-staple cotton",
      naturalPct: 100,
      origin: "Portugal",
      construction: "Single-needle, mother-of-pearl buttons",
      stock: "In stock — most sizes",
      retailer: "Caldwell.com",
      flag: null,
      reasoning: [
        ["Material", "+18", "100% cotton, pinpoint weave"],
        ["Construction", "+16", "Single-needle stitching, real MOP buttons"],
        ["Origin", "+10", "Portugal — credible shirting tradition"],
        ["Price History", "+14", "Lowest sale price recorded"],
        ["Cut", "−6", "Fit runs slim; not universally flattering"],
      ],
      history: [195,195,180,180,180,170,170,195,160,140,120,110,98,98,88],
    },
    {
      id: "trv-trouser",
      brand: "Travers",
      name: "High-twist Wool Trouser, Charcoal",
      category: "Trousers",
      grade: "great",
      gradeScore: 74,
      price: 215, was: 480, discount: 55,
      material: "100% high-twist wool (Fresco)",
      naturalPct: 100,
      origin: "Naples, Italy",
      construction: "Half-canvas waistband, side adjusters",
      stock: "Limited — 32, 34 only",
      retailer: "No Man Walks Alone",
      flag: null,
      reasoning: [
        ["Material", "+20", "Italian Fresco, breathable high-twist wool"],
        ["Construction", "+12", "Side-adjusters, real waistband canvas"],
        ["Origin", "+12", "Made in Naples"],
        ["Price History", "+8", "Frequent sale item; this is near floor"],
        ["Stock", "−6", "Two sizes only — limited utility"],
      ],
      history: [480,480,480,420,420,420,395,395,360,330,295,260,240,225,215],
    },
    {
      id: "nrt-tee",
      brand: "Northfield",
      name: "Heavyweight Pocket T-Shirt, Ecru",
      category: "Tees",
      grade: "good",
      gradeScore: 64,
      price: 32, was: 68, discount: 53,
      material: "92% cotton / 8% elastane",
      naturalPct: 92,
      origin: "Vietnam",
      construction: "Tubular knit, ribbed collar",
      stock: "In stock — all sizes",
      retailer: "Northfield",
      flag: "8% elastane",
      reasoning: [
        ["Material", "+10", "Heavyweight cotton, but with elastane"],
        ["Construction", "+10", "Tubular body, durable rib collar"],
        ["Origin", "−2", "Vietnam — fine but generic"],
        ["Synthetic content", "−8", "Elastane shortens garment lifespan"],
        ["Price History", "+8", "Sale-floor pricing"],
      ],
      history: [68,68,68,60,60,55,55,68,52,42,38,36,34,32,32],
    },
    {
      id: "hrr-coat",
      brand: "Harringate",
      name: "Loro Piana Storm-System Topcoat, Camel",
      category: "Outerwear",
      grade: "excellent",
      gradeScore: 88,
      price: 1240, was: 2895, discount: 57,
      material: "85% wool / 15% cashmere",
      naturalPct: 100,
      origin: "Lazio, Italy",
      construction: "Full canvas, hand-padded lapels, horn buttons",
      stock: "In stock — 38R, 40R, 42R",
      retailer: "Harringate",
      flag: null,
      reasoning: [
        ["Material", "+24", "Loro Piana Storm-System wool/cashmere"],
        ["Construction", "+20", "Full-canvas, hand-padded — rare at this tier"],
        ["Origin", "+16", "Made in Italy, Lazio"],
        ["Price History", "+12", "57% off — first markdown of season"],
        ["Brand markup", "−6", "Designer house margin remains"],
      ],
      history: [2895,2895,2895,2895,2895,2895,2750,2500,2200,1850,1600,1400,1240],
    },
    {
      id: "bls-blazer",
      brand: "Bowles & Stride",
      name: "Hopsack Blazer, Navy",
      category: "Tailoring",
      grade: "fair",
      gradeScore: 48,
      price: 295, was: 695, discount: 58,
      material: "55% wool / 45% polyester",
      naturalPct: 55,
      origin: "China",
      construction: "Fused canvas, plastic buttons",
      stock: "In stock",
      retailer: "Bowles & Stride",
      flag: "45% polyester",
      reasoning: [
        ["Material", "−12", "Nearly half polyester — drape will degrade"],
        ["Construction", "−10", "Fused canvas; will bubble after dry cleaning"],
        ["Origin", "−4", "Generic offshore production"],
        ["Price History", "+8", "Low recorded price"],
        ["Buttons", "−4", "Plastic, not horn or shell"],
      ],
      history: [695,695,650,650,595,595,550,495,450,395,350,320,295],
    },
    {
      id: "vlt-sweater",
      brand: "Velten",
      name: "Lambswool Roll-Neck Sweater, Oat",
      category: "Knitwear",
      grade: "great",
      gradeScore: 76,
      price: 84, was: 180, discount: 53,
      material: "100% lambswool",
      naturalPct: 100,
      origin: "Leicester, England",
      construction: "Set-in sleeves, ribbed cuffs",
      stock: "In stock — S–XL",
      retailer: "Velten",
      flag: null,
      reasoning: [
        ["Material", "+18", "100% lambswool, soft-yet-resilient"],
        ["Origin", "+14", "Made in England, established knitting region"],
        ["Construction", "+10", "Solid finishing, no shortcuts"],
        ["Price History", "+12", "Lowest in 12 months"],
        ["Brand", "+0", "Younger label, no premium yet"],
      ],
      history: [180,180,165,165,150,150,140,135,120,108,98,92,84],
    },
    {
      id: "bnd-jacket",
      brand: "Bandera",
      name: "Performance Field Jacket, Olive",
      category: "Outerwear",
      grade: "poor",
      gradeScore: 28,
      price: 145, was: 320, discount: 55,
      material: "100% recycled polyester",
      naturalPct: 0,
      origin: "Bangladesh",
      construction: "Heat-bonded seams, plastic hardware",
      stock: "In stock",
      retailer: "Bandera",
      flag: "100% polyester",
      reasoning: [
        ["Material", "−24", "Plastic. Period."],
        ["Construction", "−12", "Heat-bonded seams will fail in 2–3 years"],
        ["Marketing", "−6", "'Recycled' is a manufacturing input, not a virtue"],
        ["Price History", "+6", "Sale-floor pricing"],
        ["Origin", "−2", "Generic offshore"],
      ],
      history: [320,320,280,280,250,250,220,200,180,165,155,150,145],
    },
    {
      id: "klr-loafer",
      brand: "Kellner & Roe",
      name: "Goodyear-welted Penny Loafer, Whisky",
      category: "Footwear",
      grade: "excellent",
      gradeScore: 90,
      price: 285, was: 595, discount: 52,
      material: "Calf leather, leather sole",
      naturalPct: 100,
      origin: "Northampton, England",
      construction: "Goodyear welt, hand-finished",
      stock: "In stock — UK 8, 9, 10",
      retailer: "Kellner & Roe",
      flag: null,
      reasoning: [
        ["Material", "+20", "Full-grain calf, leather sole"],
        ["Construction", "+24", "Goodyear-welted — resoleable for decades"],
        ["Origin", "+18", "Northampton — the standard"],
        ["Price History", "+10", "First markdown of the season"],
        ["Last", "−2", "Last runs narrow"],
      ],
      history: [595,595,595,560,560,560,520,520,490,420,360,310,285],
    },
    {
      id: "fls-jeans",
      brand: "Fillmore",
      name: "Selvedge Denim, 14oz Indigo",
      category: "Denim",
      grade: "great",
      gradeScore: 80,
      price: 96, was: 215, discount: 55,
      material: "100% cotton selvedge",
      naturalPct: 100,
      origin: "Okayama, Japan",
      construction: "Chain-stitched hem, copper rivets",
      stock: "In stock — 30–36",
      retailer: "Fillmore",
      flag: null,
      reasoning: [
        ["Material", "+18", "Japanese 14oz selvedge, sanforized"],
        ["Origin", "+16", "Okayama — denim's origin region"],
        ["Construction", "+14", "Chain-stitch, copper rivets, heavy bartacks"],
        ["Price History", "+12", "First sale of this colorway"],
        ["Cut", "+0", "Standard straight"],
      ],
      history: [215,215,215,195,195,180,180,165,140,125,115,108,96],
    },
    {
      id: "stb-scarf",
      brand: "Strathblane",
      name: "Cashmere Scarf, Tartan",
      category: "Accessories",
      grade: "good",
      gradeScore: 60,
      price: 78, was: 165, discount: 53,
      material: "100% cashmere",
      naturalPct: 100,
      origin: "Inner Mongolia (woven in China)",
      construction: "Fringed ends, single-ply",
      stock: "In stock",
      retailer: "Strathblane",
      flag: null,
      reasoning: [
        ["Material", "+16", "100% cashmere — but single-ply"],
        ["Origin", "−4", "Woven in China, not Scotland"],
        ["Construction", "−6", "Single-ply will pill quickly"],
        ["Price History", "+8", "Reasonable markdown"],
        ["Versatility", "+4", "Tartan reads classic, not loud"],
      ],
      history: [165,165,150,150,140,135,120,110,100,92,85,80,78],
    },
    {
      id: "rwd-chino",
      brand: "Roundwood",
      name: "Cotton Twill Chino, Stone",
      category: "Trousers",
      grade: "fair",
      gradeScore: 44,
      price: 58, was: 125, discount: 54,
      material: "98% cotton / 2% elastane",
      naturalPct: 98,
      origin: "Egypt",
      construction: "Tunnel waistband, plastic buttons",
      stock: "In stock",
      retailer: "Roundwood",
      flag: "2% elastane",
      reasoning: [
        ["Material", "−4", "Even 2% elastane reduces lifespan"],
        ["Construction", "−6", "Tunnel waistband, no canvas"],
        ["Origin", "+4", "Egyptian cotton, decent mill"],
        ["Price History", "+8", "Reliable sale-floor"],
        ["Cut", "+0", "Generic"],
      ],
      history: [125,125,115,115,110,100,95,85,75,68,62,60,58],
    },
  ];

  const savedIds = ["abk-cardigan", "hrr-coat", "klr-loafer", "fls-jeans"];
  const alerts = [
    { id: "a1", query: "Goodyear-welted shoes, ≥A grade, under $400", matches: 7, last: "2 hr ago" },
    { id: "a2", query: "Wool sweaters, 100% natural, ≥B grade", matches: 14, last: "today" },
    { id: "a3", query: "Travers — any item", matches: 2, last: "yesterday" },
    { id: "a4", query: "Cashmere coats under $1500", matches: 3, last: "3 days ago" },
  ];

  // Per-id size availability — alpha for tops, numeric for shoes/denim
  // status: "in" = available · "low" = low stock · "out" = sold out
  const SIZE_DATA = {
    "abk-cardigan": { kind: "alpha", sizes: [["XS","in"],["S","in"],["M","low"],["L","in"],["XL","out"]] },
    "drk-oxford":   { kind: "neck",  sizes: [["14.5","out"],["15","in"],["15.5","in"],["16","low"],["16.5","in"],["17","out"]] },
    "trv-trouser":  { kind: "waist", sizes: [["30","in"],["32","low"],["34","in"],["36","in"],["38","out"],["40","out"]] },
    "nrt-tee":      { kind: "alpha", sizes: [["S","in"],["M","in"],["L","in"],["XL","in"],["XXL","low"]] },
    "hrr-coat":     { kind: "alpha", sizes: [["38","out"],["40","low"],["42","in"],["44","in"],["46","out"],["48","out"]] },
    "bls-blazer":   { kind: "alpha", sizes: [["38R","in"],["40R","in"],["42R","low"],["44R","in"],["46R","out"]] },
    "vlt-sweater":  { kind: "alpha", sizes: [["S","low"],["M","in"],["L","in"],["XL","in"]] },
    "bnd-jacket":   { kind: "alpha", sizes: [["S","in"],["M","in"],["L","in"],["XL","in"],["XXL","in"]] },
    "klr-loafer":   { kind: "us",    sizes: [["8","in"],["8.5","low"],["9","in"],["9.5","out"],["10","in"],["10.5","in"],["11","low"],["12","out"]] },
    "fls-jeans":    { kind: "waist", sizes: [["28","in"],["29","low"],["30","in"],["31","in"],["32","in"],["33","low"],["34","out"],["36","out"]] },
    "stb-scarf":    { kind: "one",   sizes: [["One size","in"]] },
    "rwd-chino":    { kind: "waist", sizes: [["30","in"],["32","in"],["34","in"],["36","in"],["38","low"],["40","out"]] },
  };
  items.forEach(it => {
    const d = SIZE_DATA[it.id];
    if (d) { it.sizeKind = d.kind; it.sizes = d.sizes; }
  });

  return { items, savedIds, alerts };
})();
